// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SmartWatch

#include "ui.h"
#include "ui_ClockScreen.h"
#include <Arduino.h>
#include "uiWeatherScreen.h"

static constexpr const char* MAIN_DEFAULT_TITLE = "Ætherwatch";

void ui_MainScreen_reset_menu_default(void)
{
    if (ui_MainArcMenu != NULL && lv_obj_is_valid(ui_MainArcMenu)) {
        lv_arc_set_value(ui_MainArcMenu, 0);
        lv_arc_set_start_angle(ui_MainArcMenu, 120);
        lv_arc_set_end_angle(ui_MainArcMenu, 180);
    }

    if (ui_screenselectlabel != NULL && lv_obj_is_valid(ui_screenselectlabel)) {
        lv_label_set_text(ui_screenselectlabel, MAIN_DEFAULT_TITLE);
    }
}

void mainarc_valuechange(lv_event_t * e)
{
    int arcvalue = lv_arc_get_value(ui_MainArcMenu);
    int total_angle = 300;
    int section_angle = total_angle / 5;
    int indicator_start_angle = 120;
    int indicator_end_angle = 120 + section_angle;
    const char *label_text = MAIN_DEFAULT_TITLE;

    if(arcvalue >= 0 && arcvalue < 100) {
        indicator_start_angle = 120;
        indicator_end_angle = 120 + section_angle;
        label_text = MAIN_DEFAULT_TITLE;
    } else if(arcvalue >= 100 && arcvalue < 200) {
        indicator_start_angle = 120 + section_angle;
        indicator_end_angle = 120 + 2 * section_angle;
        label_text = "Clock";
    } else if(arcvalue >= 200 && arcvalue < 300) {
        indicator_start_angle = 120 + 2 * section_angle;
        indicator_end_angle = 120 + 3 * section_angle;
        label_text = "Music Controls";
    } else if(arcvalue >= 300 && arcvalue < 400) {
        indicator_start_angle = 120 + 3 * section_angle;
        indicator_end_angle = 120 + 4 * section_angle;
        label_text = "Settings";
    } else if(arcvalue >= 400 && arcvalue <= 500) {
        indicator_start_angle = 120 + 4 * section_angle;
        indicator_end_angle = 120 + 5 * section_angle;
        label_text = "Weather";
    }

    lv_arc_set_start_angle(ui_MainArcMenu, indicator_start_angle);
    lv_arc_set_end_angle(ui_MainArcMenu, indicator_end_angle);

    if(ui_screenselectlabel != NULL) {
        lv_label_set_text(ui_screenselectlabel, label_text);
    } else {
        Serial.println("Error: ui_screenselectlabel is NULL");
    }
}

void mainarc_select(lv_event_t * e)
{
    int arcvalue = lv_arc_get_value(ui_MainArcMenu);

    if(arcvalue >= 0 && arcvalue < 100) {
        ui_MainScreen_reset_menu_default();
        return;
    } else if(arcvalue >= 100 && arcvalue < 200) {
        if (ui_MainArcClockMenu) {
            lv_arc_set_start_angle(ui_MainArcClockMenu, 180);
            lv_arc_set_end_angle(ui_MainArcClockMenu, 240);
        }
        printf("switching to clock Screen\n");
        _ui_screen_change(&ui_ClockScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 50, ui_ClockScreen_screen_init);
    } else if(arcvalue >= 200 && arcvalue < 300) {
        if (ui_MainArcMenuMusic) {
            lv_arc_set_start_angle(ui_MainArcMenuMusic, 240);
            lv_arc_set_end_angle(ui_MainArcMenuMusic, 300);
        }
        _ui_screen_change(&ui_MusicControls, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, ui_MusicControls_screen_init);
    } else if(arcvalue >= 300 && arcvalue < 400) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 200, 50, ui_Settings_screen_init);
    } else if(arcvalue >= 400 && arcvalue <= 500) {
        _ui_screen_change(&ui_WeatherScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_WeatherScreen_screen_init);
    }
}

void mainarcclock_valuechange(lv_event_t * e)
{
    int arcvalue = lv_arc_get_value(ui_MainArcClockMenu);
    int total_angle = 300;
    int section_angle = total_angle / 5;
    int indicator_start_angle = 120;
    int indicator_end_angle = 120 + section_angle;

    if(arcvalue >= 0 && arcvalue < 100) {
        indicator_start_angle = 120;
        indicator_end_angle = 120 + section_angle;
    } else if(arcvalue >= 100 && arcvalue < 200) {
        indicator_start_angle = 120 + section_angle;
        indicator_end_angle = 120 + 2 * section_angle;
    } else if(arcvalue >= 200 && arcvalue < 300) {
        indicator_start_angle = 120 + 2 * section_angle;
        indicator_end_angle = 120 + 3 * section_angle;
    } else if(arcvalue >= 300 && arcvalue < 400) {
        indicator_start_angle = 120 + 3 * section_angle;
        indicator_end_angle = 120 + 4 * section_angle;
    } else if(arcvalue >= 400 && arcvalue <= 500) {
        indicator_start_angle = 120 + 4 * section_angle;
        indicator_end_angle = 120 + 5 * section_angle;
    }

    lv_arc_set_start_angle(ui_MainArcClockMenu, indicator_start_angle);
    lv_arc_set_end_angle(ui_MainArcClockMenu, indicator_end_angle);
}

void mainarcclock_select(lv_event_t * e)
{
    int arcvalue = lv_arc_get_value(ui_MainArcClockMenu);

    if(arcvalue >= 0 && arcvalue < 100) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 50, ui_MainScreen_screen_init);
        ui_MainScreen_reset_menu_default();
    } else if(arcvalue >= 100 && arcvalue < 200) {
        return;
    } else if(arcvalue >= 200 && arcvalue < 300) {
        if (ui_MainArcMenuMusic) {
            lv_arc_set_start_angle(ui_MainArcMenuMusic, 240);
            lv_arc_set_end_angle(ui_MainArcMenuMusic, 300);
        }
        _ui_screen_change(&ui_MusicControls, LV_SCR_LOAD_ANIM_FADE_ON, 200, 50, ui_MusicControls_screen_init);
    } else if(arcvalue >= 300 && arcvalue < 400) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 200, 50, ui_Settings_screen_init);
    } else if(arcvalue >= 400 && arcvalue <= 500) {
        _ui_screen_change(&ui_WeatherScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_WeatherScreen_screen_init);
    }
}

void mainarcmusic_valuechange(lv_event_t * e)
{
    int arcvalue = lv_arc_get_value(ui_MainArcMenuMusic);
    int total_angle = 300;
    int section_angle = total_angle / 5;
    int indicator_start_angle = 120;
    int indicator_end_angle = 120 + section_angle;

    if(arcvalue >= 0 && arcvalue < 100) {
        indicator_start_angle = 120;
        indicator_end_angle = 120 + section_angle;
    } else if(arcvalue >= 100 && arcvalue < 200) {
        indicator_start_angle = 120 + section_angle;
        indicator_end_angle = 120 + 2 * section_angle;
    } else if(arcvalue >= 200 && arcvalue < 300) {
        indicator_start_angle = 120 + 2 * section_angle;
        indicator_end_angle = 120 + 3 * section_angle;
    } else if(arcvalue >= 300 && arcvalue < 400) {
        indicator_start_angle = 120 + 3 * section_angle;
        indicator_end_angle = 120 + 4 * section_angle;
    } else if(arcvalue >= 400 && arcvalue <= 500) {
        indicator_start_angle = 120 + 4 * section_angle;
        indicator_end_angle = 120 + 5 * section_angle;
    }

    lv_arc_set_start_angle(ui_MainArcMenuMusic, indicator_start_angle);
    lv_arc_set_end_angle(ui_MainArcMenuMusic, indicator_end_angle);
}

void mainarcmusic_select(lv_event_t * e)
{
    int arcvalue = lv_arc_get_value(ui_MainArcMenuMusic);

    if(arcvalue >= 0 && arcvalue < 100) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, ui_MainScreen_screen_init);
        ui_MainScreen_reset_menu_default();
    } else if(arcvalue >= 100 && arcvalue < 200) {
        if (ui_MainArcClockMenu) {
            lv_arc_set_start_angle(ui_MainArcClockMenu, 180);
            lv_arc_set_end_angle(ui_MainArcClockMenu, 240);
        }
        _ui_screen_change(&ui_ClockScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, ui_ClockScreen_screen_init);
    } else if(arcvalue >= 200 && arcvalue < 300) {
        return;
    } else if(arcvalue >= 300 && arcvalue < 400) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, ui_Settings_screen_init);
    } else if(arcvalue >= 400 && arcvalue <= 500) {
        _ui_screen_change(&ui_WeatherScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_WeatherScreen_screen_init);
    }
}

void musictrack_release(lv_event_t * e)
{
    // Your code here
}

void playbutton_pressed(lv_event_t * e)
{
    // Your code here
}

void prevbutton_pressed(lv_event_t * e)
{
    // Your code here
}

void nextbutton_pressed(lv_event_t * e)
{
    // Your code here
}

void mainarcsettings_valuechange(lv_event_t * e)
{
    // Settings screen now uses its own radial menu implementation in ui_Settings.cpp.
}

void mainarcsettings_select(lv_event_t * e)
{
    // Settings screen now uses its own radial menu implementation in ui_Settings.cpp.
}
