// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SmartWatch

#include "ui_Settings.h"
#include "DisplayManager.h"
#include "SettingsManager.h"
#include "ui_SettingsLocation.h"
#include "ui_KeyboardOverlay.h"
//#include "mc_circular_keyboard.h"

#include <algorithm>

lv_obj_t * arc_segments[NUM_SEGMENTS];
const char * segment_labels[NUM_SEGMENTS] = {"Wi-Fi", "General", "Home", "Bluetooth", "Weather", "Sound"};



lv_obj_t * wifi_list;
lv_obj_t * content_area;
lv_obj_t * ui_SettingsRadialMenu;
lv_obj_t * content_label;
static lv_obj_t * password_kb;
int segment_index;
bool doScreenBrightnessUpdate;

static const char *keyboard_context = nullptr;

// ----- Wi-Fi settings UI state -----
static lv_obj_t * wifi_status_label = nullptr;
static lv_obj_t * wifi_action_panel = nullptr;
static lv_obj_t * wifi_password_textarea = nullptr;
static lv_timer_t * wifi_scan_timer = nullptr;

static String wifi_selected_ssid;
static std::vector<String> wifi_scan_ssids;
static bool wifi_page_active = false;

static bool wifi_is_enabled()
{
    wifi_mode_t mode = WiFi.getMode();
    return mode == WIFI_STA || mode == WIFI_AP_STA;
}

static bool wifi_selected_is_connected()
{
    return WiFi.status() == WL_CONNECTED && WiFi.SSID() == wifi_selected_ssid;
}

static void wifi_set_status(const char * text)
{
    if (wifi_status_label) {
        lv_label_set_text(wifi_status_label, text);
    }
}

static void wifi_stop_scan_timer()
{
    if (wifi_scan_timer) {
        lv_timer_del(wifi_scan_timer);
        wifi_scan_timer = nullptr;
    }
}

static void wifi_clear_action_panel()
{
    wifi_password_textarea = nullptr;

    if (!wifi_action_panel) return;

    lv_obj_clean(wifi_action_panel);
    lv_obj_add_flag(wifi_action_panel, LV_OBJ_FLAG_HIDDEN);
}

static lv_obj_t * wifi_add_panel_button(const char * text, lv_event_cb_t cb, void * user_data)
{
    if (!wifi_action_panel) return nullptr;

    lv_obj_t * btn = lv_btn_create(wifi_action_panel);
    lv_obj_set_width(btn, lv_pct(90));
    lv_obj_set_height(btn, 34);

    lv_obj_t * label = lv_label_create(btn);
    lv_label_set_text(label, text);
    lv_obj_center(label);

    lv_obj_add_event_cb(btn, cb, LV_EVENT_CLICKED, user_data);
    return btn;
}

static void wifi_render_known_networks_only()
{
    if (!wifi_list) return;

    lv_obj_clean(wifi_list);
    lv_list_add_text(wifi_list, "Saved networks");

    if (currentSettings.known_wifi_networks.empty()) {
        lv_obj_t * btn = lv_list_add_btn(wifi_list, NULL, "No saved networks");
        lv_obj_add_state(btn, LV_STATE_DISABLED);
        return;
    }

    for (auto & network : currentSettings.known_wifi_networks) {
        const char * icon = (WiFi.status() == WL_CONNECTED && WiFi.SSID() == network.ssid)
            ? LV_SYMBOL_OK
            : LV_SYMBOL_WIFI;

        lv_obj_t * btn = lv_list_add_btn(wifi_list, icon, network.ssid.c_str());
        lv_obj_add_event_cb(btn, saved_network_selected_cb, LV_EVENT_CLICKED, (void *)network.ssid.c_str());
    }
}

static bool wifi_scan_ssid_already_listed(const String& ssid)
{
    for (const auto& existing : wifi_scan_ssids) {
        if (existing == ssid) return true;
    }
    return false;
}

static void wifi_render_network_list_from_scan()
{
    if (!wifi_list) return;

    lv_obj_clean(wifi_list);

    if (!currentSettings.known_wifi_networks.empty()) {
        lv_list_add_text(wifi_list, "Saved networks");

        for (auto & network : currentSettings.known_wifi_networks) {
            const char * icon = (WiFi.status() == WL_CONNECTED && WiFi.SSID() == network.ssid)
                ? LV_SYMBOL_OK
                : LV_SYMBOL_WIFI;

            lv_obj_t * btn = lv_list_add_btn(wifi_list, icon, network.ssid.c_str());
            lv_obj_add_event_cb(btn, saved_network_selected_cb, LV_EVENT_CLICKED, (void *)network.ssid.c_str());
        }
    }

    lv_list_add_text(wifi_list, "Found networks");

    if (wifi_scan_ssids.empty()) {
        lv_obj_t * btn = lv_list_add_btn(wifi_list, NULL, "No networks found");
        lv_obj_add_state(btn, LV_STATE_DISABLED);
        return;
    }

    for (auto & ssid : wifi_scan_ssids) {
        int saved_index = findKnownWiFiNetworkIndex(ssid);
        const char * icon = saved_index >= 0 ? LV_SYMBOL_OK : LV_SYMBOL_WIFI;

        lv_obj_t * btn = lv_list_add_btn(wifi_list, icon, ssid.c_str());
        lv_obj_add_event_cb(btn, wifi_network_selected_cb, LV_EVENT_CLICKED, (void *)ssid.c_str());

        if (saved_index >= 0) {
            lv_obj_set_style_text_color(btn, lv_color_hex(0x41C7FF), 0);
        }
    }
}

static void wifi_build_password_entry_panel(const char * title, bool show_save, bool show_connect)
{
    if (!wifi_action_panel) return;

    wifi_clear_action_panel();
    lv_obj_clear_flag(wifi_action_panel, LV_OBJ_FLAG_HIDDEN);

    lv_obj_t * title_label = lv_label_create(wifi_action_panel);
    lv_label_set_text(title_label, title);
    lv_obj_set_width(title_label, lv_pct(90));
    lv_label_set_long_mode(title_label, LV_LABEL_LONG_DOT);
    lv_obj_set_style_text_font(title_label, &lv_font_montserrat_12, 0);

    wifi_password_textarea = lv_textarea_create(wifi_action_panel);
    lv_obj_set_width(wifi_password_textarea, lv_pct(90));
    lv_obj_set_height(wifi_password_textarea, 38);
    lv_textarea_set_one_line(wifi_password_textarea, true);
    lv_textarea_set_password_mode(wifi_password_textarea, true);
    lv_textarea_set_placeholder_text(wifi_password_textarea, "Password");

    ui_keyboard_attach_textarea(wifi_password_textarea, content_area);

    if (show_save) {
        wifi_add_panel_button("Save", save_wifi_network_event_cb, wifi_password_textarea);
    }

    if (show_connect) {
        wifi_add_panel_button("Connect", connect_wifi_network_event_cb, wifi_password_textarea);
    }
}

static void wifi_disconnect_selected_event_cb(lv_event_t * e)
{
    (void)e;

    if (wifi_selected_ssid.length() == 0) return;

    if (wifi_selected_is_connected()) {
        WiFi.disconnect(false);
        wifi_set_status("Disconnected");
    }

    wifi_clear_action_panel();

    if (wifi_scan_ssids.empty()) {
        wifi_render_known_networks_only();
    } else {
        wifi_render_network_list_from_scan();
    }
}

static void wifi_build_selected_network_panel()
{
    if (!wifi_action_panel) return;

    wifi_clear_action_panel();
    lv_obj_clear_flag(wifi_action_panel, LV_OBJ_FLAG_HIDDEN);

    lv_obj_t * title = lv_label_create(wifi_action_panel);
    lv_label_set_text(title, wifi_selected_ssid.c_str());
    lv_obj_set_width(title, lv_pct(90));
    lv_label_set_long_mode(title, LV_LABEL_LONG_DOT);
    lv_obj_set_style_text_font(title, &lv_font_montserrat_12, 0);

    int saved_index = findKnownWiFiNetworkIndex(wifi_selected_ssid);

    if (saved_index >= 0) {
        wifi_add_panel_button("Connect", connect_wifi_network_event_cb, nullptr);
        wifi_add_panel_button("Change password", edit_saved_network_event_cb, (void *)wifi_selected_ssid.c_str());
        wifi_add_panel_button("Forget", remove_saved_network_event_cb, (void *)wifi_selected_ssid.c_str());

        if (wifi_selected_is_connected()) {
            wifi_add_panel_button("Disconnect", wifi_disconnect_selected_event_cb, nullptr);
        }
    } else {
        wifi_build_password_entry_panel(wifi_selected_ssid.c_str(), true, true);
    }
}

static void wifi_scan_timer_cb(lv_timer_t * timer)
{
    (void)timer;

    if (!wifi_page_active || !wifi_list) {
        wifi_stop_scan_timer();
        return;
    }

    int result = WiFi.scanComplete();

    if (result == WIFI_SCAN_RUNNING) {
        static uint8_t dots = 0;
        dots = (dots + 1) % 4;

        if (dots == 0) wifi_set_status("Scanning");
        else if (dots == 1) wifi_set_status("Scanning.");
        else if (dots == 2) wifi_set_status("Scanning..");
        else wifi_set_status("Scanning...");
        return;
    }

    if (result == WIFI_SCAN_FAILED) {
        wifi_stop_scan_timer();
        wifi_set_status("Scan failed");
        WiFi.scanDelete();
        wifi_render_known_networks_only();
        return;
    }

    wifi_stop_scan_timer();

    wifi_scan_ssids.clear();

    for (int i = 0; i < result; ++i) {
        String ssid = WiFi.SSID(i);
        if (ssid.length() == 0) continue;
        if (wifi_scan_ssid_already_listed(ssid)) continue;

        wifi_scan_ssids.push_back(ssid);
    }

    WiFi.scanDelete();

    if (wifi_scan_ssids.empty()) {
        wifi_set_status("No networks found");
    } else {
        String status = "Found ";
        status += String(wifi_scan_ssids.size());
        status += " network";
        if (wifi_scan_ssids.size() != 1) status += "s";
        wifi_set_status(status.c_str());
    }

    wifi_render_network_list_from_scan();
}

static void wifi_start_async_scan()
{
    wifi_stop_scan_timer();

    if (!wifi_list) return;

    wifi_enable();
    WiFi.scanDelete();

    wifi_scan_ssids.clear();
    wifi_clear_action_panel();

    wifi_set_status("Scanning...");
    lv_obj_clean(wifi_list);
    lv_list_add_text(wifi_list, "Scanning");
    lv_obj_t * wait_btn = lv_list_add_btn(wifi_list, LV_SYMBOL_REFRESH, "Searching for networks...");
    lv_obj_add_state(wait_btn, LV_STATE_DISABLED);

    int start_result = WiFi.scanNetworks(true);

    if (start_result >= 0) {
        // Some builds can return results immediately.
        wifi_scan_timer_cb(nullptr);
        return;
    }

    wifi_scan_timer = lv_timer_create(wifi_scan_timer_cb, 250, nullptr);
}


void create_content_area(void) {
    content_area = lv_obj_create(ui_Settings);
    lv_obj_set_size(content_area, 240, 240); // Adjust size to avoid overlapping with symbols
    lv_obj_center(content_area);
    lv_obj_add_flag(content_area, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(content_area, lv_color_white(), 0);
    lv_obj_set_style_radius(content_area, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_scrollbar_mode(content_area, LV_SCROLLBAR_MODE_AUTO);

   // lv_obj_set_style_pad_all(content_area, 10, 0); // Add padding if needed

    
}

void handle_keyboard_close(bool is_ok_pressed) {
    if (is_ok_pressed) {
        printf("OK pressed. Context: %s\n", keyboard_context);

        if (strcmp(keyboard_context, "sound_settings") == 0) {
            // Handle OK for sound settings
            printf("Handle OK for sound settings.\n");
        } else if (strcmp(keyboard_context, "wifi_password") == 0) {
            // Handle OK for WiFi password
            printf("Save WiFi password.\n");
        } else if (strcmp(keyboard_context, "bluetooth_name") == 0) {
            // Handle OK for Bluetooth device name
            printf("Save Bluetooth device name.\n");
        }
        // Add more contexts as needed
    } else {
        printf("Cancel pressed. Restoring radial menu and buttons.\n");
    }

    // Always restore the radial menu on close
    show_radial_menu_and_buttons();
}


void show_wifi_settings(void) {
    wifi_page_active = true;
    wifi_selected_ssid = "";
    wifi_password_textarea = nullptr;

    wifi_stop_scan_timer();

    lv_obj_clean(content_area);

    lv_obj_set_flex_flow(content_area, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(content_area, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    content_label = lv_label_create(content_area);
    lv_label_set_text(content_label, "Wi-Fi Settings");
    lv_obj_set_style_text_font(content_label, &lv_font_montserrat_12, 0);

    lv_obj_t * wifi_switch = lv_switch_create(content_area);
    lv_obj_add_event_cb(wifi_switch, wifi_switch_event_cb, LV_EVENT_VALUE_CHANGED, NULL);

    if (wifi_is_enabled()) {
        lv_obj_add_state(wifi_switch, LV_STATE_CHECKED);
    }

    wifi_status_label = lv_label_create(content_area);
    lv_obj_set_width(wifi_status_label, lv_pct(90));
    lv_label_set_long_mode(wifi_status_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_font(wifi_status_label, &lv_font_montserrat_12, 0);

    wifi_list = lv_list_create(content_area);
    lv_obj_set_size(wifi_list, lv_pct(90), 115);
    lv_obj_set_style_pad_all(wifi_list, 4, 0);

    wifi_action_panel = lv_obj_create(content_area);
    lv_obj_set_width(wifi_action_panel, lv_pct(90));
    lv_obj_set_height(wifi_action_panel, 125);
    lv_obj_set_flex_flow(wifi_action_panel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(wifi_action_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(wifi_action_panel, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_add_flag(wifi_action_panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(wifi_action_panel, LV_OBJ_FLAG_HIDDEN);

    if (wifi_is_enabled()) {
        wifi_set_status("Wi-Fi on");
        scan_and_display_wifi_networks();
    } else {
        wifi_set_status("Wi-Fi off. Saved networks shown.");
        wifi_render_known_networks_only();
    }
}


void show_sleep_settings(void) {
    //lv_obj_clean(content_area); // Clear previous content

    content_label = lv_label_create(content_area);
    lv_label_set_text(content_label, "Sleep Timer");
    lv_obj_align(content_label, LV_ALIGN_TOP_MID, 0, 20);

    // Create sleep timer slider
    lv_obj_t * slider = lv_slider_create(content_area);
    lv_obj_set_width(slider, lv_pct(80));
    lv_obj_align(slider, LV_ALIGN_CENTER, 0, 30);
    lv_slider_set_range(slider, 5, 60);
    lv_slider_set_value(slider, currentSettings.sleep_duration, LV_ANIM_OFF);
    lv_obj_add_event_cb(slider, sleep_timer_slider_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
}

void create_radial_menu(void)
{
// Create the arc
    ui_SettingsRadialMenu = lv_arc_create(ui_Settings);
    lv_obj_set_size(ui_SettingsRadialMenu, 460, 460);
    lv_obj_center(ui_SettingsRadialMenu);
    lv_arc_set_bg_angles(ui_SettingsRadialMenu, 0, 360); // Full circle
    lv_arc_set_range(ui_SettingsRadialMenu, 0, 600);
   // lv_arc_set_value(ui_SettingsRadialMenu, 0);
    lv_obj_set_style_arc_width(ui_SettingsRadialMenu, 50, LV_PART_MAIN); // Adjust thickness
    lv_obj_set_style_arc_width(ui_SettingsRadialMenu, 50, LV_PART_INDICATOR); // Adjust thickness
    lv_obj_set_style_arc_color(ui_SettingsRadialMenu, lv_color_hex(0x2c2836), LV_PART_MAIN);
    
    //lv_obj_remove_style(ui_SettingsRadialMenu, NULL, LV_PART_KNOB); // Remove knob
    // Make the knob invisible but functional
    lv_obj_set_style_bg_opa(ui_SettingsRadialMenu, LV_OPA_TRANSP, LV_PART_KNOB);

    lv_obj_set_style_arc_rounded(ui_SettingsRadialMenu, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_arc_set_rotation(ui_SettingsRadialMenu, -90);


    lv_obj_set_align(ui_SettingsRadialMenu, LV_ALIGN_CENTER);

    lv_obj_clear_flag(ui_SettingsRadialMenu, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_SettingsRadialMenu, LV_OBJ_FLAG_SCROLLABLE);

    // Initialize the indicator to the first segment
    lv_arc_set_start_angle(ui_SettingsRadialMenu, 0);
    lv_arc_set_end_angle(ui_SettingsRadialMenu, 360 / NUM_SEGMENTS);

}


void ui_Settings_screen_init(void)
{
    Serial.println("ui_Settings_screen_init was called");
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x100820), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_size(ui_Settings, 466, 466);
    ui_keyboard_overlay_init(ui_Settings);

    create_radial_menu();
    create_content_area();
     add_segment_buttons(); // Use this if you're creating buttons
}

void add_segment_buttons(void) {
    int angle_per_segment = 360 / NUM_SEGMENTS;
    const char * segment_symbols[NUM_SEGMENTS] = {LV_SYMBOL_WIFI, LV_SYMBOL_SETTINGS, LV_SYMBOL_HOME, LV_SYMBOL_BLUETOOTH, LV_SYMBOL_REFRESH, LV_SYMBOL_AUDIO};

    for (int i = 0; i < NUM_SEGMENTS; i++) {
        int mid_angle = i * angle_per_segment + angle_per_segment / 2;
        int radius = 150; // Adjust radius to position the button within the segment
        mid_angle -= 90;
        if (mid_angle <= 0) {
            mid_angle += 360;
        }

        // Convert angle to radians
        float rad = mid_angle * 3.14159265 / 180.0;

        int x = (int)(radius * cos(rad));
        int y = (int)(radius * sin(rad));

        // Create a button for the segment
        lv_obj_t * btn = lv_btn_create(ui_Settings);
        if (!btn) {
            printf("Error: Failed to create segment button %d\n", i);
            continue;
        }

        arc_segments[i] = btn; // Store the button in the arc_segments array

        lv_obj_set_style_radius(btn, LV_RADIUS_CIRCLE, 0);
        lv_obj_set_size(btn, 40, 40); // Adjust size as needed
        lv_obj_align(btn, LV_ALIGN_CENTER, x, y);
        lv_obj_set_style_bg_opa(btn, LV_OPA_TRANSP, 0); // Make button background transparent
        lv_obj_set_style_border_opa(btn, LV_OPA_TRANSP, LV_PART_MAIN);
        lv_obj_set_style_shadow_width(btn, 0, 0);

        // Create a label for the symbol inside the button
        lv_obj_t * symbol_label = lv_label_create(btn);
        lv_label_set_text(symbol_label, segment_symbols[i]);
        lv_obj_align(symbol_label, LV_ALIGN_CENTER, 0, 0);
        lv_obj_set_style_text_font(symbol_label, &lv_font_montserrat_24, 0); // Adjust font size as needed
        lv_obj_set_style_text_color(symbol_label, lv_color_white(), 0); // Set text color
        lv_obj_set_style_text_color(symbol_label, lv_color_hex(0x79CBFC), LV_STATE_PRESSED);

        // Assign the segment index as user data
        lv_obj_set_user_data(btn, (void *)(intptr_t)i);
        //lv_obj_set_style_pad_all(btn, 30, LV_STATE_PRESSED);
        lv_obj_set_ext_click_area(btn, 10);
        // Add event callback to the button
        lv_obj_add_event_cb(btn, segment_btn_event_cb, LV_EVENT_CLICKED, NULL);
    }
}


void segment_btn_event_cb(lv_event_t * e)
{
    lv_obj_t * btn = (lv_obj_t *)lv_event_get_target(e);
    int segment_index = (int)(intptr_t)lv_obj_get_user_data(btn);

    if (!ui_SettingsRadialMenu) {
        return;  // Ensure the radial menu is valid
    }

    if (segment_index != 0) {
    wifi_page_active = false;
    wifi_stop_scan_timer();
    WiFi.scanDelete();
    wifi_status_label = nullptr;
    wifi_action_panel = nullptr;
    wifi_password_textarea = nullptr;
    }

    // Update the arc's indicator to highlight the selected segment
    int total_angle = 360;
    int section_angle = total_angle / NUM_SEGMENTS;
    
    int indicator_start_angle = segment_index * section_angle;
    int indicator_end_angle = (segment_index + 1) * section_angle;

    lv_arc_set_start_angle(ui_SettingsRadialMenu, indicator_start_angle);
    lv_arc_set_end_angle(ui_SettingsRadialMenu, indicator_end_angle);

    // Perform the action based on the segment index
    switch(segment_index) {
        case 0: // Wi-Fi
            show_wifi_settings();
            break;
        case 1: // General
            show_general_settings();
            break;
        case 2: // Home
            // Time to save the settings.
               saveSettingsDataToFile("/settings.json", currentSettings);
            _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, ui_MainScreen_screen_init);
            break;
        case 3: // Bluetooth
            show_bluetooth_settings();
            break;
        case 4: // Weather
            show_weather();
            break;
        case 5: // Sound
            show_sound_settings();
            break;
        default:
            break;
    }
}

void arc_event_cb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_PRESSING) {
        settingsMenu_valuechange(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        settingsMenu_select(e);
    }
}

void settingsMenu_valuechange(lv_event_t * e)
{
    lv_obj_t * arc = (lv_obj_t *)lv_event_get_target(e);

// Get the touch point coordinates
    lv_indev_t * indev = lv_indev_get_act();
    lv_point_t touch_point;
    lv_indev_get_point(indev, &touch_point);

    // Get the arc's center coordinates
    lv_area_t arc_coords;
    lv_obj_get_coords(arc, &arc_coords);
    lv_coord_t arc_center_x = arc_coords.x1 + lv_area_get_width(&arc_coords) / 2;
    lv_coord_t arc_center_y = arc_coords.y1 + lv_area_get_height(&arc_coords) / 2;

    // Calculate the difference in x and y from the center
    int dx = touch_point.x - arc_center_x;
    int dy = arc_center_y - touch_point.y ;

    // Calculate the angle in degrees (0 to 360)
    float angle = atan2f(dx, dy) * (180.0f / 3.14159265f);
    if (angle < 0) {
        angle += 360.0f;
    }



    // Adjust the angle based on the arc's rotation
   // angle -= 90.0f; // Since we rotated the arc by -90 degrees
    if (angle < 0) {
        angle += 360.0f;
    }

    // Calculate the segment index

    float segment_angle = 360.0f / NUM_SEGMENTS;
     segment_index = (int)(angle / segment_angle);
    if(segment_index >= NUM_SEGMENTS) segment_index = 0;

    // Update the arc's indicator to highlight the selected segment
    int indicator_start_angle = segment_index * segment_angle;
    int indicator_end_angle = (segment_index + 1) * segment_angle;

    lv_arc_set_start_angle(arc, indicator_start_angle);
    lv_arc_set_end_angle(arc, indicator_end_angle);

    // Debug output
    Serial.printf("dx: %d, dy: %d, angle: %.2f, segment_index: %d\n", dx, dy, angle, segment_index);

}

void settingsMenu_select(lv_event_t * e)
{
    lv_obj_t * arc = (lv_obj_t *)lv_event_get_target(e);

    // Debug output
    Serial.printf("Segment Selected: %d\n", segment_index);

    if (segment_index != 0) {
    wifi_page_active = false;
    wifi_stop_scan_timer();
    WiFi.scanDelete();
    wifi_status_label = nullptr;
    wifi_action_panel = nullptr;
    wifi_password_textarea = nullptr;
}

    // Perform the action based on the segment index
    switch(segment_index) {
        case 0: // Wi-Fi
            show_wifi_settings();
            break;
        case 1: // General
            show_general_settings();
            break;
        case 2: // Home
         //lv_arc_set_start_angle(ui_MainArcMenu, 120);
         //lv_arc_set_end_angle(ui_MainArcMenu, 180);
         //lv_label_set_text(ui_screenselectlabel, "Main");
         lv_arc_set_value(ui_MainArcMenu, 0);
            _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, ui_MainScreen_screen_init);
            break;
        case 3: // Bluetooth
            show_bluetooth_settings();
            break;
        case 4: // Weather
            show_weather();
            break;
        case 5: // Sound
            show_sound_settings();
            break;
        default:
            break;
    }
}
 
void hide_radial_menu_and_buttons(void) {
    if (ui_SettingsRadialMenu) {
        lv_obj_add_flag(ui_SettingsRadialMenu, LV_OBJ_FLAG_HIDDEN); // Hide the radial menu
    }

    for (int i = 0; i < NUM_SEGMENTS; i++) {
        if (arc_segments[i]) {
            lv_obj_add_flag(arc_segments[i], LV_OBJ_FLAG_HIDDEN); // Hide each segment button
            printf("Hid arc_segment[%d] \n", i);
        } else {
            printf("Warning: arc_segments[%d] is NULL\n", i);
        }
    }
}


void show_radial_menu_and_buttons(void) {
    if (ui_SettingsRadialMenu) {
        if (!lv_obj_is_valid(ui_SettingsRadialMenu)) {
            printf("Warning: ui_SettingsRadialMenu is invalid.\n");
            return;
        }
        lv_obj_clear_flag(ui_SettingsRadialMenu, LV_OBJ_FLAG_HIDDEN); // Show the radial menu
    } else {
        printf("Warning: ui_SettingsRadialMenu is NULL.\n");
    }

    for (int i = 0; i < NUM_SEGMENTS; i++) {
        if (arc_segments[i]) {
            if (!lv_obj_is_valid(arc_segments[i])) {
                printf("Warning: arc_segments[%d] is invalid.\n", i);
                continue;
            }
            lv_obj_clear_flag(arc_segments[i], LV_OBJ_FLAG_HIDDEN); // Show each segment button
            printf("Shown arc_segments[%d].\n", i);
        } else {
            printf("Warning: arc_segments[%d] is NULL.\n", i);
        }
    }
}



// **Wi-Fi Switch Event Callback** 
void wifi_switch_event_cb(lv_event_t *e) {
    lv_obj_t *sw = (lv_obj_t *)lv_event_get_target(e);

    wifi_clear_action_panel();

    if (lv_obj_has_state(sw, LV_STATE_CHECKED)) {
        scan_and_display_wifi_networks();
    } else {
        wifi_stop_scan_timer();
        WiFi.scanDelete();
        wifi_disable();

        wifi_scan_ssids.clear();
        wifi_set_status("Wi-Fi off. Saved networks shown.");
        wifi_render_known_networks_only();
    }
}


void brightness_slider_event_cb(lv_event_t * e) {
    lv_obj_t * slider = (lv_obj_t *)lv_event_get_target(e);
    
 
        uint8_t value = lv_slider_get_value(slider);
        
        // Ensure value is not below 10
        if (value < 10) {
            value = 10;
            lv_slider_set_value(slider, value, LV_ANIM_ON);
        }
        currentSettings.brightness_level = value;
        
       // Serial.printf("Slider value changed: %d\n", value);
      // Serial.printf("Settings Brightness Level is set to: %d\n", currentSettings.brightness_level);
      //  powerManager.setBacklightBrightness(value);
    

}

void brightness_slider_released_event_cb(lv_event_t *e) {
    lv_obj_t *slider = (lv_obj_t *)lv_event_get_target(e);
    uint8_t value = lv_slider_get_value(slider);
    currentSettings.brightness_level = value;
    DisplayManager::instance().setBrightness(value);

    Serial.printf("Slider released, final value: %d\n", value);
   

    // Make sure brightness is properly updated
  //  powerManager.setBacklightBrightness(value);
}



void sleep_timer_slider_event_cb(lv_event_t * e) {
    lv_obj_t * slider = (lv_obj_t *)lv_event_get_target(e);
    uint8_t value = lv_slider_get_value(slider);
    // Adjust the sleep timer accordingly
    // Implement set_sleep_timer(value);
}

void show_general_settings(void) {
    lv_obj_clean(content_area); // Clear previous content

    // Use a flex layout to arrange labels and sliders in a column
    lv_obj_set_flex_flow(content_area, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(content_area, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER); 
    
    content_label = lv_label_create(content_area);
    lv_label_set_text(content_label, "General Settings");
    lv_obj_set_style_text_font(content_label, &lv_font_montserrat_12, 0);

    // Brightness Label
    lv_obj_t * brightness_label = lv_label_create(content_area);
    lv_label_set_text(brightness_label, "Display");

    // Brightness Slider
    lv_obj_t * brightness_slider = lv_slider_create(content_area);
    lv_obj_set_width(brightness_slider, lv_pct(80));
    lv_slider_set_range(brightness_slider, 10, 255);
    lv_obj_add_flag(brightness_slider, LV_OBJ_FLAG_CLICKABLE);
    lv_slider_set_value(brightness_slider, currentSettings.brightness_level, LV_ANIM_ON);
    lv_obj_set_style_anim_duration(brightness_slider, 2000, 0);
    lv_obj_add_event_cb(brightness_slider, brightness_slider_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(brightness_slider, brightness_slider_released_event_cb, LV_EVENT_RELEASED, NULL);

    // Sleep Timer Label
    lv_obj_t * sleep_timer_label = lv_label_create(content_area);
    lv_label_set_text(sleep_timer_label, "Sleep Timer");

    // Sleep Timer Slider
    lv_obj_t * sleep_timer_slider = lv_slider_create(content_area);
    lv_obj_set_width(sleep_timer_slider, lv_pct(80));
    lv_slider_set_range(sleep_timer_slider, 5, 60);
    lv_slider_set_value(sleep_timer_slider, currentSettings.sleep_duration, LV_ANIM_OFF);
    lv_obj_add_event_cb(sleep_timer_slider, sleep_timer_slider_event_cb, LV_EVENT_VALUE_CHANGED, NULL);

    //Location Setings Call
    ui_settings_add_location_controls(content_area);

}

// Event callback for Bluetooth switch
void bluetooth_switch_event_cb(lv_event_t * e) {
    lv_obj_t * switch_obj = (lv_obj_t *) lv_event_get_target(e);
    bool bt_on = lv_obj_has_state(switch_obj, LV_STATE_CHECKED);
    
    if(bt_on) {
       // enable_bluetooth();  // Function to enable Bluetooth in your code
        //populate_device_list(); // Function to update device list
    } else {
        //disable_bluetooth(); // Function to disable Bluetooth in your code
        //lv_list_clean(bt_device_list); // Clear the device list
    }
}

// Callback functions for connect, disconnect, pair actions
void connect_btn_event_cb(lv_event_t * e) {
    const char * device_name = (const char *)lv_event_get_user_data(e);
    Serial.printf("Connecting to: %s\n", device_name);
    //connect_bluetooth_device(device_name);
}

void disconnect_btn_event_cb(lv_event_t * e) {
    const char * device_name = (const char *)lv_event_get_user_data(e);
    Serial.printf("Disconnecting from: %s\n", device_name);
    //disconnect_bluetooth_device(device_name);
}

void pair_btn_event_cb(lv_event_t * e) {
    const char * device_name = (const char *)lv_event_get_user_data(e);
    Serial.printf("Pairing with: %s\n", device_name);
    //pair_bluetooth_device(device_name);
}


// Event callback for selecting a Bluetooth device
void device_select_event_cb(lv_event_t * e) {
    lv_obj_t * btn = (lv_obj_t*)lv_event_get_target(e);
    const char * device_name = lv_list_get_button_text(bt_device_list, btn);
    Serial.printf("Selected device: %s\n", device_name);

    // Show the action container with connect/pair/disconnect buttons
    lv_obj_clear_flag(action_container, LV_OBJ_FLAG_HIDDEN);

    // Clean any previous buttons from action_container
    lv_obj_clean(action_container);

    // Add buttons for connect, disconnect, pair
    lv_obj_t * connect_btn = lv_btn_create(action_container);
    lv_obj_align(connect_btn, LV_ALIGN_LEFT_MID, 20, 0);
    lv_obj_t * connect_label = lv_label_create(connect_btn);
    lv_label_set_text(connect_label, "Connect");
    lv_obj_add_event_cb(connect_btn, connect_btn_event_cb, LV_EVENT_CLICKED, (void*)device_name);

    lv_obj_t * disconnect_btn = lv_btn_create(action_container);
    lv_obj_align(disconnect_btn, LV_ALIGN_CENTER, 0, 0);
    lv_obj_t * disconnect_label = lv_label_create(disconnect_btn);
    lv_label_set_text(disconnect_label, "Disconnect");
    lv_obj_add_event_cb(disconnect_btn, disconnect_btn_event_cb, LV_EVENT_CLICKED, (void*)device_name);

    lv_obj_t * pair_btn = lv_btn_create(action_container);
    lv_obj_align(pair_btn, LV_ALIGN_RIGHT_MID, -20, 0);
    lv_obj_t * pair_label = lv_label_create(pair_btn);
    lv_label_set_text(pair_label, "Pair");
    lv_obj_add_event_cb(pair_btn, pair_btn_event_cb, LV_EVENT_CLICKED, (void*)device_name);
}


void show_bluetooth_settings(void) {
    
    lv_obj_clean(content_area); // Clear previous content

    // Label
    content_label = lv_label_create(content_area);
    lv_label_set_text(content_label, "Bluetooth Settings");
    lv_obj_align(content_label, LV_ALIGN_TOP_MID, 0, 10);

    // Create Bluetooth switch
    lv_obj_t * bt_switch = lv_switch_create(content_area);
    lv_obj_align(bt_switch, LV_ALIGN_TOP_LEFT, 20, 40);
    lv_obj_add_event_cb(bt_switch, bluetooth_switch_event_cb, LV_EVENT_VALUE_CHANGED, NULL);

    // Label for the switch
    lv_obj_t * switch_label = lv_label_create(content_area);
    lv_label_set_text(switch_label, "Bluetooth On/Off");
    lv_obj_align_to(switch_label, bt_switch, LV_ALIGN_OUT_RIGHT_MID, 10, 0);

    // Create list for available devices
    bt_device_list = lv_list_create(content_area);
    lv_obj_set_size(bt_device_list, lv_pct(90), lv_pct(40));
    lv_obj_align(bt_device_list, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_pad_all(bt_device_list, 5, 0);

    // Add sample devices (this should be updated dynamically based on available devices)
    lv_obj_t * list_btn = lv_list_add_btn(bt_device_list, LV_SYMBOL_BLUETOOTH, "Device 1");
    lv_obj_add_event_cb(list_btn, device_select_event_cb, LV_EVENT_CLICKED, bt_device_list);

    list_btn = lv_list_add_btn(bt_device_list, LV_SYMBOL_BLUETOOTH, "Device 2");
    lv_obj_add_event_cb(list_btn, device_select_event_cb, LV_EVENT_CLICKED, bt_device_list);

    // Container for actions (connect, disconnect, pair)
    action_container = lv_obj_create(content_area);
    lv_obj_set_size(action_container, lv_pct(90), 60);
    lv_obj_align(action_container, LV_ALIGN_BOTTOM_MID, 0, -10);
    lv_obj_set_style_bg_color(action_container, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_border_width(action_container, 1, 0);
    lv_obj_set_style_radius(action_container, 5, 0);
    lv_obj_add_flag(action_container, LV_OBJ_FLAG_HIDDEN);
}


void show_weather(void) {
   lv_obj_clean(content_area); // Clear previous content

    content_label = lv_label_create(content_area);
    lv_label_set_text(content_label, "Weather");
    lv_obj_align(content_label, LV_ALIGN_TOP_MID, 0, 10);

    // Display weather information here
}

void show_sound_settings(void) {
    lv_obj_clean(content_area); // Clear previous content

    content_label = lv_label_create(content_area);
    lv_label_set_text(content_label, "Sound Settings");
    lv_obj_align(content_label, LV_ALIGN_TOP_MID, 0, 10);

    // Hide the radial menu and associated buttons
    hide_radial_menu_and_buttons();

    // Set the keyboard context
    keyboard_context = "sound_settings";

    // Create the circular keyboard
    lv_obj_t * scr = lv_scr_act();




/* // 2) Create the keyboard on the screen
    lv_obj_t * test_keyboard = mc_circular_keyboard_create(scr, 180); 
  // e.g. radius=100
    if (!test_keyboard) {
        printf("Error: Circular keyboard creation failed.\n");
    } else {
        printf("Circular keyboard created successfully.\n");

        // Set keyboard properties
        mc_circular_keyboard_set_band_style(test_keyboard, lv_color_hex(0x0078D7), 30); // Set band color and thickness
        mc_circular_keyboard_set_style(test_keyboard, lv_color_hex(0xFFFFFF), lv_color_hex(0x000000), false); // Set key styles

        // Position the keyboard in the center
      //  mc_circular_keyboard_set_position(test_keyboard, 180, 180);

        // Set the "on close" callback
        mc_circular_keyboard_set_on_close(test_keyboard, []() {
            handle_keyboard_close(false); // Pass `false` for cancel
        });

        // Set the "OK button" callback
        mc_circular_keyboard_set_on_ok(test_keyboard, []() {
            handle_keyboard_close(true); // Pass `true` for OK
        });
    }
 */
    // Add sound settings controls here
}


// Wi-Fi Enable Function
void wifi_enable() {
    WiFi.mode(WIFI_STA);
    WiFi.setSleep(false);
    WiFi.disconnect(); // Ensure we're starting fresh
}

// Wi-Fi Disable Function
void wifi_disable() {
    WiFi.disconnect(true);
    WiFi.scanDelete();
    WiFi.mode(WIFI_OFF);
}
    // Define the close callback function
    void close_keyboard_callback(lv_event_t *e) {
        lv_obj_t *kb = (lv_obj_t *) lv_event_get_target(e);

        // Retrieve the user data stored in the keyboard
       // lv_obj_t **ui_elements = (lv_obj_t **)lv_obj_get_user_data(kb);
       // lv_obj_t *password_box = ui_elements[0];
       // lv_obj_t *save_btn = ui_elements[1];
       // lv_obj_t *connect_btn = ui_elements[2];

        // Clean up UI elements
        //lv_obj_del(password_box);
        //lv_obj_del(save_btn);
        //lv_obj_del(connect_btn);
        lv_obj_del(kb);

        // Optionally show other UI elements or reset state
      //  lv_obj_clear_flag(ui_SettingsRadialMenu, LV_OBJ_FLAG_HIDDEN);

       // free(ui_elements); // Free the allocated memory
    }

void save_btn_cb(lv_event_t *e) {
    lv_obj_t *password_box = (lv_obj_t *)lv_event_get_user_data(e);
    if (!password_box) return; // Ensure password_box is valid

    const char *password = lv_textarea_get_text(password_box);
    Serial.printf("Saving network with password: %s\n", password);

    // Cleanup
    lv_obj_t *circular_keyboard = (lv_obj_t *)lv_obj_get_user_data(password_box);
    if (circular_keyboard) lv_obj_del(circular_keyboard);
    lv_obj_del(password_box);
    lv_obj_clear_flag(ui_SettingsRadialMenu, LV_OBJ_FLAG_HIDDEN);
}

void connect_btn_cb(lv_event_t *e) {
    lv_obj_t *password_box = (lv_obj_t *)lv_event_get_user_data(e);
    if (!password_box) return; // Ensure password_box is valid

    const char *password = lv_textarea_get_text(password_box);
    Serial.printf("Connecting to network with password: %s\n", password);

    // Cleanup
    lv_obj_t *circular_keyboard = (lv_obj_t *)lv_obj_get_user_data(password_box);
    if (circular_keyboard) lv_obj_del(circular_keyboard);
    lv_obj_del(password_box);
    lv_obj_clear_flag(ui_SettingsRadialMenu, LV_OBJ_FLAG_HIDDEN);
}

void cancel_btn_cb(lv_event_t *e) {
    lv_obj_t *password_box = (lv_obj_t *)lv_event_get_user_data(e);
    if (!password_box) return; // Ensure password_box is valid

    // Cleanup
    lv_obj_t *circular_keyboard = (lv_obj_t *)lv_obj_get_user_data(password_box);
    if (circular_keyboard) lv_obj_del(circular_keyboard);
    lv_obj_del(password_box);
    lv_obj_clear_flag(ui_SettingsRadialMenu, LV_OBJ_FLAG_HIDDEN);
}

// WiFi network selection callback
// WiFi network selection callback
void wifi_network_selected_cb(lv_event_t * e)
{
    const char * selected_ssid = (const char *)lv_event_get_user_data(e);
    if (!selected_ssid || selected_ssid[0] == '\0') {
        Serial.println("Error: No SSID provided.");
        return;
    }

    wifi_selected_ssid = String(selected_ssid);
    Serial.printf("Selected SSID: %s\n", wifi_selected_ssid.c_str());

    wifi_build_selected_network_panel();
}

// Saved network selection callback
void saved_network_selected_cb(lv_event_t *e) {
    const char *selected_ssid = (const char *)lv_event_get_user_data(e);
    if (!selected_ssid || selected_ssid[0] == '\0') {
        Serial.println("Error: No saved SSID provided.");
        return;
    }

    wifi_selected_ssid = String(selected_ssid);
    Serial.printf("Selected saved SSID: %s\n", wifi_selected_ssid.c_str());

    wifi_build_selected_network_panel();
}

// Save new WiFi network event callback
void save_wifi_network_event_cb(lv_event_t *e) {
    lv_obj_t *password_box = (lv_obj_t *)lv_event_get_user_data(e);
    if (!password_box) {
        password_box = wifi_password_textarea;
    }

    if (!password_box || wifi_selected_ssid.length() == 0) {
        Serial.println("Save WiFi failed: missing password box or selected SSID.");
        return;
    }

    const char *password = lv_textarea_get_text(password_box);
    addOrUpdateKnownWiFiNetwork(wifi_selected_ssid, String(password), true);

    currentSettings.wifi_ssid = wifi_selected_ssid;
    currentSettings.wifi_ssd = wifi_selected_ssid;
    currentSettings.wifi_pass = String(password);

    saveSettingsDataToFile("/settings.json", currentSettings);

    Serial.printf("Saved SSID: %s\n", wifi_selected_ssid.c_str());
    wifi_set_status("Network saved");

    wifi_build_selected_network_panel();

    if (wifi_scan_ssids.empty()) {
        wifi_render_known_networks_only();
    } else {
        wifi_render_network_list_from_scan();
    }
}

// Edit saved network password event callback
void edit_saved_network_event_cb(lv_event_t *e) {
    const char *selected_ssid = (const char *)lv_event_get_user_data(e);
    if (selected_ssid && selected_ssid[0] != '\0') {
        wifi_selected_ssid = String(selected_ssid);
    }

    if (wifi_selected_ssid.length() == 0) {
        Serial.println("Edit WiFi failed: no selected SSID.");
        return;
    }

    String title = "New password for ";
    title += wifi_selected_ssid;

    wifi_build_password_entry_panel(title.c_str(), true, true);
}

// This name is kept because it is declared in ui_Settings.h.
// The real save path now goes through save_wifi_network_event_cb().
void save_updated_password_event_cb(lv_event_t * e) {
    save_wifi_network_event_cb(e);
}

// Remove saved WiFi network event callback
void remove_saved_network_event_cb(lv_event_t *e) {
    const char *selected_ssid = (const char *)lv_event_get_user_data(e);
    if (selected_ssid && selected_ssid[0] != '\0') {
        wifi_selected_ssid = String(selected_ssid);
    }

    if (wifi_selected_ssid.length() == 0) {
        Serial.println("Remove WiFi failed: no selected SSID.");
        return;
    }

    Serial.printf("Removing SSID: %s\n", wifi_selected_ssid.c_str());

    removeKnownWiFiNetwork(wifi_selected_ssid);

    if (currentSettings.wifi_ssid == wifi_selected_ssid) currentSettings.wifi_ssid = "";
    if (currentSettings.wifi_ssd == wifi_selected_ssid) currentSettings.wifi_ssd = "";
    if (WiFi.SSID() == wifi_selected_ssid) WiFi.disconnect(false);

    saveSettingsDataToFile("/settings.json", currentSettings);

    wifi_selected_ssid = "";
    wifi_clear_action_panel();
    wifi_set_status("Network forgotten");

    if (wifi_scan_ssids.empty()) {
        wifi_render_known_networks_only();
    } else {
        wifi_render_network_list_from_scan();
    }
}

void connect_wifi_network_event_cb(lv_event_t * e) {
    lv_obj_t * password_box = (lv_obj_t *)lv_event_get_user_data(e);

    if (wifi_selected_ssid.length() == 0) {
        Serial.println("Connect WiFi failed: no selected SSID.");
        return;
    }

    String password;

    if (password_box) {
        password = String(lv_textarea_get_text(password_box));
    }

    if (password.length() == 0) {
        int saved_index = findKnownWiFiNetworkIndex(wifi_selected_ssid);
        if (saved_index >= 0) {
            password = currentSettings.known_wifi_networks[saved_index].password;
        }
    }

    if (password.length() == 0) {
        wifi_build_password_entry_panel(wifi_selected_ssid.c_str(), true, true);
        wifi_set_status("Password required");
        return;
    }

    addOrUpdateKnownWiFiNetwork(wifi_selected_ssid, password, true);

    currentSettings.wifi_ssid = wifi_selected_ssid;
    currentSettings.wifi_ssd = wifi_selected_ssid;
    currentSettings.wifi_pass = password;

    saveSettingsDataToFile("/settings.json", currentSettings);

    wifi_enable();

    Serial.printf("Connecting to SSID: %s\n", wifi_selected_ssid.c_str());
    WiFi.begin(wifi_selected_ssid.c_str(), password.c_str());

    wifi_set_status("Connecting...");
    wifi_build_selected_network_panel();

    if (wifi_scan_ssids.empty()) {
        wifi_render_known_networks_only();
    } else {
        wifi_render_network_list_from_scan();
    }
}

// Display WiFi networks (saved and scanned)
void scan_and_display_wifi_networks() {
    if (wifi_list == nullptr) {
        Serial.println("Error in scan & display networks: Wi-Fi list is not initialized.");
        return;
    }

    wifi_start_async_scan();
}